global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "bot"
    static_configs:
      - targets: ['host.docker.internal:8890']
  - job_name: "scrapper"
    static_configs:
      - targets: ['host.docker.internal:8880']
