app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

api:
  github:
    url: https://api.github.com
  stackoverflow:
    url: https://api.stackexchange.com
  bot:
    url: http://localhost:8090
  link-updater:
    interval: 10000
    limit:  100


spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
